package view;

/**
 *
 * @author Igor J Rodrigues
 */
public class DialogDesenhos extends javax.swing.JDialog {
    private Panel2D panel;
    /**
     * Creates new form DialogDesenhos
     */
    public DialogDesenhos(java.awt.Frame parent, boolean modal, String title, String tipo) {
        super(parent, modal);
        initComponents();
        this.setTitle(title);
        criarPanel(tipo);
    }

    private void criarPanel(String tipo){
        switch (tipo) {
            case "bresenham" -> {
                panel = new PanelBresenhamLine();   
                panel.setSize(this.getSize());
                this.add(panel);
            }
            case "linear" -> {
                panel = new PanelLineLinear();   
                panel.setSize(this.getSize());
                this.add(panel);
            }
            case "parametric" -> {
                panel = new PanelLineParametric();   
                panel.setSize(this.getSize());
                this.add(panel);
            }
            case "circleNormal" -> {
                panel = new PanelCircleNormal();   
                panel.setSize(this.getSize());
                this.add(panel);
            }
            case "circleParametric" -> {
                panel = new PanelCircleParametric();   
                panel.setSize(this.getSize());
                this.add(panel);
            }
            case "circleBresenham" -> {
                panel = new PanelCircleBresenham();   
                panel.setSize(this.getSize());
                this.add(panel);
            }
            default -> throw new AssertionError();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
