package view;

/**
 *
 * @author Igor J Rodrigues
 */
public class DialogImagem extends javax.swing.JDialog {
    private String imgPath;
    PanelImagem panelImg;
    /**
     * Creates new form DialogImagem
     */
    public DialogImagem(java.awt.Frame parent, boolean modal, String imgPath) {
        super(parent, modal);
        initComponents(); 
        this.imgPath = imgPath;
        
        panelImg = new PanelImagem(imgPath);
        this.add(panelImg);
        this.setLayout(null);
        panelImg.setLocation(0, 0);
        panelImg.setSize(1000, 750);
        panelImg.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCinza = new javax.swing.JButton();
        jButtonRestaurar = new javax.swing.JButton();
        jButtonNegativo = new javax.swing.JButton();
        jButtonCanalR = new javax.swing.JButton();
        jButtonCanalG = new javax.swing.JButton();
        jButtonCanalB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButtonCinza.setText("Tons de Cinza");
        jButtonCinza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCinzaActionPerformed(evt);
            }
        });

        jButtonRestaurar.setText("Restaurar");
        jButtonRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestaurarActionPerformed(evt);
            }
        });

        jButtonNegativo.setText("Negativo");
        jButtonNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegativoActionPerformed(evt);
            }
        });

        jButtonCanalR.setText("Canal R");
        jButtonCanalR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanalRActionPerformed(evt);
            }
        });

        jButtonCanalG.setText("Canal G");
        jButtonCanalG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanalGActionPerformed(evt);
            }
        });

        jButtonCanalB.setText("Canal B");
        jButtonCanalB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCanalBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(565, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonCinza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCanalB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCanalG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCanalR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNegativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRestaurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButtonCinza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNegativo)
                .addGap(41, 41, 41)
                .addComponent(jButtonCanalR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCanalG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCanalB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jButtonRestaurar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCinzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCinzaActionPerformed
        // TODO add your handling code here:
        panelImg.operacoes("cinza");
    }//GEN-LAST:event_jButtonCinzaActionPerformed

    private void jButtonRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestaurarActionPerformed
        // TODO add your handling code here:
        panelImg.operacoes("restaurar");
    }//GEN-LAST:event_jButtonRestaurarActionPerformed

    private void jButtonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegativoActionPerformed
        // TODO add your handling code here:
        panelImg.operacoes("negativo");
    }//GEN-LAST:event_jButtonNegativoActionPerformed

    private void jButtonCanalRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanalRActionPerformed
        // TODO add your handling code here:
        panelImg.operacoes("r");
    }//GEN-LAST:event_jButtonCanalRActionPerformed

    private void jButtonCanalGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanalGActionPerformed
        // TODO add your handling code here:
        panelImg.operacoes("g");
    }//GEN-LAST:event_jButtonCanalGActionPerformed

    private void jButtonCanalBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCanalBActionPerformed
        // TODO add your handling code here:
        panelImg.operacoes("b");
    }//GEN-LAST:event_jButtonCanalBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanalB;
    private javax.swing.JButton jButtonCanalG;
    private javax.swing.JButton jButtonCanalR;
    private javax.swing.JButton jButtonCinza;
    private javax.swing.JButton jButtonNegativo;
    private javax.swing.JButton jButtonRestaurar;
    // End of variables declaration//GEN-END:variables
}
