package view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import model.Graficos2D;

/**
 *
 * @author Igor J Rodrigues
 */
public class Panel2D extends javax.swing.JPanel {
    ArrayList<Point> points;
    Point p1;
    Point p2;
    
    
    /**
     * Creates new form Panel2D
     */
    public Panel2D() {
        initComponents();
        
        points = new ArrayList<Point>();
        this.setBackground(Color.white);
        p1 = new Point(0, 0);
        p2 = new Point(400, 400);
        repaint();
        setVisible(true);	
    }
    
    @Override
	protected void paintComponent(Graphics g) {
		super.paintComponent(g);
		if(p1 == null || p2 == null) {
			return;
		}
		g.setColor(Color.black);
		for(Point p : Graficos2D.drawLine(p1, p2)) {
			g.fillOval(p.x, p.y, 5, 5);
		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
