package View;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Lucas Ikeda e Igor Rodrigues
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        arquivo = new javax.swing.JMenu();
        carregarIMG = new javax.swing.JMenuItem();
        converterRGBparaHSL = new javax.swing.JMenuItem();
        img = new javax.swing.JMenu();
        negativaIMG = new javax.swing.JMenuItem();
        desenharIMG = new javax.swing.JMenuItem();
        retas = new javax.swing.JMenu();
        retaLinear = new javax.swing.JMenuItem();
        retaParametrica = new javax.swing.JMenuItem();
        retaBresenham = new javax.swing.JMenuItem();
        circunferencia = new javax.swing.JMenu();
        circEq = new javax.swing.JMenuItem();
        circParametrica = new javax.swing.JMenuItem();
        circBresenham = new javax.swing.JMenuItem();
        projecao3D = new javax.swing.JMenu();
        jMenuItemCasinha = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        titulo.setFont(titulo.getFont().deriveFont(titulo.getFont().getStyle() | java.awt.Font.BOLD, titulo.getFont().getSize()+30));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Trabalho Computação Gráfica");

        arquivo.setText("Arquivo");

        carregarIMG.setText("Carregar");
        carregarIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarIMGActionPerformed(evt);
            }
        });
        arquivo.add(carregarIMG);

        converterRGBparaHSL.setText("Converter RGB para HSL");
        arquivo.add(converterRGBparaHSL);

        menu.add(arquivo);

        img.setText("Imagem");

        negativaIMG.setText("Negativar");
        negativaIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativaIMGActionPerformed(evt);
            }
        });
        img.add(negativaIMG);

        desenharIMG.setText("Desenhar");
        desenharIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desenharIMGActionPerformed(evt);
            }
        });
        img.add(desenharIMG);

        menu.add(img);

        retas.setText("Retas");

        retaLinear.setText("Função linear");
        retaLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retaLinearActionPerformed(evt);
            }
        });
        retas.add(retaLinear);

        retaParametrica.setText("Função paramétrica");
        retas.add(retaParametrica);

        retaBresenham.setText("Bresenham");
        retas.add(retaBresenham);

        menu.add(retas);

        circunferencia.setText("Circunferências");

        circEq.setText("Equação");
        circunferencia.add(circEq);

        circParametrica.setText("Função paramétrica");
        circParametrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circParametricaActionPerformed(evt);
            }
        });
        circunferencia.add(circParametrica);

        circBresenham.setText("Bresenham");
        circunferencia.add(circBresenham);

        menu.add(circunferencia);

        projecao3D.setText("Projeção 3D");

        jMenuItemCasinha.setText("Casinha");
        jMenuItemCasinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCasinhaActionPerformed(evt);
            }
        });
        projecao3D.add(jMenuItemCasinha);

        menu.add(projecao3D);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(titulo)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarIMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carregarIMGActionPerformed

    private void negativaIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativaIMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_negativaIMGActionPerformed

    private void desenharIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desenharIMGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desenharIMGActionPerformed

    private void retaLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retaLinearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retaLinearActionPerformed

    private void circParametricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circParametricaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circParametricaActionPerformed

    private void jMenuItemCasinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCasinhaActionPerformed
        // TODO add your handling code here:
        Projecao3D projecao = new Projecao3D();
        projecao.setLocationRelativeTo(this);
        projecao.setVisible(true);
    }//GEN-LAST:event_jMenuItemCasinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projecao3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projecao3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projecao3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projecao3D.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new FlatIntelliJLaf());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
                }
                UIManager.getLookAndFeelDefaults().put("defaultFont", new Font("Comic Sans MS", Font.PLAIN, 14));
                new Screen().setVisible(true);
            }
            
        });
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu arquivo;
    private javax.swing.JMenuItem carregarIMG;
    private javax.swing.JMenuItem circBresenham;
    private javax.swing.JMenuItem circEq;
    private javax.swing.JMenuItem circParametrica;
    private javax.swing.JMenu circunferencia;
    private javax.swing.JMenuItem converterRGBparaHSL;
    private javax.swing.JMenuItem desenharIMG;
    private javax.swing.JMenu img;
    private javax.swing.JMenuItem jMenuItemCasinha;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem negativaIMG;
    private javax.swing.JMenu projecao3D;
    private javax.swing.JMenuItem retaBresenham;
    private javax.swing.JMenuItem retaLinear;
    private javax.swing.JMenuItem retaParametrica;
    private javax.swing.JMenu retas;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
